default:
  outputs:
    dev:
      type: databricks
      schema: default
      host: "{{ env_var('DBT_ENV_SECRET_DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DBT_ENV_SECRET_DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DBT_ENV_SECRET_DATABRICKS_TOKEN') }}"
      connect_retries: 5
      connect_timeout: 60
  target: dev
